### ISSUE TITLE
加入SciSharp社区

### ISSUE THREAD

**Issue by Oceania2018** [jiaguoxinzhi/MLBot#1]
你好！我是SciSharp团队的开发，看到你这个项目很开心，因为我们终于看到了SciSharp给.NET生态带来的示范效应起效果了。感谢你能够开源你的聊天机器人项目，并且提到了BotSharp这个项目，为推广.NET应用做了很好示范。

不过有一点我不太明白，你这个项目和BotSharp有什么区别？为什么不加入SciSharp社区，集中社区力量去完善BotSharp呢？目前SciSharp的社区资源非常匮乏，导致无人维护和发展BotSharp，非常期待有开发者加入。

**Comment by jiaguoxinzhi** [comment]
目前主要还是瞎玩
